# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
masthead_title: "Home"
title: InfoSec Adventures
email: flikkme@gmail.com
author:
  name: Matt Sorrell
  bio: "Pentester/Red Teamer"
  location: "California"
  links:
  - label: "Home"
    icon: "fas fa-fw fa-link"
    url: "https://imflikk.github.io"
  - label: "Github"
    icon: "fab fa-fw fa-github"
    url: "https://github.com/imflikk"
  - label: "Twitter"
    icon: "fab fa-fw fa-twitter-square"
    url: "https://twitter.com/iamflikk"
  - label: "LinkedIn"
    icon: "fab fa-fw fa-linkedin"
    url: "https://www.linkedin.com/in/matthew-sorrell/"
    
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/iamflikk"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/imflikk"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/matthew-sorrell/"

description: >- # this means to ignore newlines until "baseurl:"
  Mostly cybersecurity and/or pentesting t I find interesting.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://imflikk.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: iamflikk
github_username:  imflikk

# Build settings
markdown: kramdown
#theme: jekyll-theme-hacker

# Theme config
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "dark"
search: true
timezone: "America/Los_Angeles"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

plugins:
  - jekyll-feed
  - jekyll-include-cache
  

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
